apiVersion: v1
kind: Pod

metadata:
  name: nicksblog-pod
  labels:
    app: nicksblog

spec:
  containers:
    - name: nicksblog-container
      image: nicksegal/devops-nicksblog:latest
      ports: 
        - name: gunicorn
          containerPort: 8000
          protocol: TCP
      env:
        - name: BLOGPASSWORD
          valueFrom:
            secretKeyRef:
              name: blogpassword
              key: BLOGPASSWORD
        - name: DJANGOKEY
          valueFrom:
            secretKeyRef:
              name: djangokey
              key: DJANGOKEY
