apiVersion: v1
kind: Service

metadata:
  name: nicksblog-service

spec:
  type: NodePort
  ports: 
    - targetPort: 8000
      port: 80
      nodePort: 30001
  selector:
    app: nicksblog
  externalIPs:
    - 172.105.179.246
