apiVersion: v1
kind: Pod

metadata:
  name: nicksblog-pod
  labels:
    app: nicksblog

spec:
  containers:
    - name: nicksblog-container
      image: nicksegal/devops-nicksblog:6361ba0a-5c71-46e0-a535-ae7a3a5f00cb
      ports: 
        - name: gunicorn
          containerPort: 8000
          protocol: TCP
      env:
        - name: BLOGPASSWORD
          valueFrom:
            secretKeyRef:
              name: blogpassword
              key: BLOGPASSWORD
        - name: DJANGOKEY
          valueFrom:
            secretKeyRef:
              name: djangokey
              key: DJANGOKEY
        - name: AWSACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: awsaccesskeyid
              key: AWSACCESSKEYID
        - name: AWSSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: awssecretaccesskey
              key: AWSSECRETACCESSKEY 